header:
  logo: "assets/logo.png"
  text: "EoE TaMMA"
stringecy: "padj_0.1"
github:
  private_repo: True
  username: "daneseomics"
  token: "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"
  repo_name: "Danese-Omics-Web-Apps/eoe_tamma_data"
credentials:
  use_credentials: True
  username: "ungaro"
  pass: "steams"
sorted_conditions: False
condition_list:
  - Healthy_GFP
  - Healthy_MFSD2A_GFP
  - Healthy_shCTRL
  - Healthy_shMFSD2A
  - CRC_GFP
  - CRC_MFSD2A_GFP
  - CRC_shCTRL
  - CRC_shMFSD2A
add_external_resources_to_dge_table: False
external_resources:
  IBD exome browser:
    icon: "assets/icon_ibd_exome.png"
    link_root: https://ibd.broadinstitute.org/gene/
    column_to_use: "Gene ID"
opentargets: False
