browser_tab_name: "EoE TaMMA"

#github options
github:
  private_repo: True
  username: "daneseomics"
  token: "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"

repos:
  "EoE TaMMA":
    analysis: "EoE TaMMA"
    logo: "assets/eoe_tamma_logo.png"
    path: "DU-omics/eoe-meta-analysis_data/master/"
    stringency: "padj_1e-5"
    default_comparison: "Esophagus_EoE-vs-Esophagus_Control"
    best_comparisons:
      - "Blood_EoE-vs-Blood_Control"
      - "Blood_EoE-vs-Blood_GERD"
      - "Blood_GERD-vs-Blood_Control"
      - "Esophagus_EoE-vs-Esophagus_Control"
      - "Esophagus_EoE-vs-Esophagus_GERD"
      - "Esophagus_GERD-vs-Esophagus_Control"
    sorted_conditions: False
    condition_list: []

#web app credentials
credentials:
  use_credentials: True
  username: "ungaro"
  pass: "steams"

#external resources
add_external_resources_to_dge_table: False
external_resources:
  IBD exome browser:
    icon: "assets/icon_ibd_exome.png"
    link_root: https://ibd.broadinstitute.org/gene/
    column_to_use: "Gene ID"

#opentargets
opentargets: False

palette:
  - "#1f78b4"
  - "#33A02C"
  - "#E31A1C"
  - "#6A3D9A"
  - "#B15928"
  - "#3B5DFF"
  - "#FF7F00"
  - "#008941"
  - "#D53E4F"
  - "#CAB2D6"
  - "#CCAA35"
  - "#A6CEE3"
  - "#B3DE69"
  - "#FDAE61"
  - "#3288BD"
  - "#F46D43"
  - "#B2DF8A"
  - "#5E4FA2"
  - "#F4D749"
  - "#FDB462"
  - "#BC80BD"
  - "#009131"
  - "#FB9A99"
  - "#FED976"
  - "#ABDDA4"
  - "#8FB0FF"
  - "#BB8BFF"
  - "#CC002B"
  - "#FB8072"
  - "#CDA727"
  - "#0A09AE"
  - "#5D00B9"
  - "#772600"
  - "#F7924C"
  - "#FAD09F"
  - "#006C31"
  - "#5B93FF"
  - "#5C006A"
  - "#FF3944"
  - "#BEAC3B"
  - "#C48700"
  - "#008531"
  - "#4C43ED"
  - "#BC29E1"
  - "#AB2E00"
  - "#E69A49"
  - "#00B433"
  - "#0000A6"
  - "#6300A3"
  - "#6B002C"
  - "#CA834E"
  - "#9FA064"
  - "#002DB5"
  - "#9F94F0"
